// SPDX-License-Identifier: GPL-2.0

//! Rust driver for Open Profile for DICE.
//!
//! Port of drivers/misc/open-dice.c.
//!
//! This driver takes ownership of a reserved memory region containing data
//! generated by the Open Profile for DICE measured boot protocol. The memory
//! contents are not interpreted by the kernel but can be mapped into a
//! userspace process via a misc device. Userspace can also request a wipe of
//! the memory.
//!
//! Userspace can access the data with (w/o error handling):
//!
//! ```ignore
//! fd = open("/dev/open-dice0", O_RDWR);
//! read(fd, &size, sizeof(unsigned long));
//! data = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
//! write(fd, NULL, 0); // wipe
//! close(fd);
//! ```

use core::sync::atomic::{AtomicU32, Ordering};

use kernel::{
    bindings,
    container_of,
    device::{self, Core},
    error::to_result,
    fs::{File, Kiocb},
    iov::{IovIterDest, IovIterSource},
    miscdevice::{MiscDevice, MiscDeviceOptions, MiscDeviceRegistration},
    mm::virt::{flags, VmaNew},
    new_mutex,
    of,
    page::PAGE_SIZE,
    platform,
    prelude::*,
    str::CString,
    sync::{Arc, Mutex},
    types::ForeignOwnable, //
};

/// Prefix used to format the per-instance misc device name (`DRIVER_NAME`).
const DRIVER_NAME_PREFIX: &str = "open-dice";

/// Index counter shared by all probed instances, mirroring the C driver's
/// `static unsigned int dev_idx`.
static DEV_IDX: AtomicU32 = AtomicU32::new(0);

/// State shared between a device instance and all open file descriptors.
///
/// # Invariants
///
/// `base` and `size` describe a page-aligned reserved memory region with
/// non-zero size and are never modified after construction.
#[pin_data]
struct WipeState {
    /// Physical base address of the reserved memory region.
    base: bindings::phys_addr_t,
    /// Size of the reserved memory region in bytes.
    size: usize,
    /// Guards wipe operations (map + memset + unmap), like `drvdata->lock`
    /// in the C driver.
    #[pin]
    lock: Mutex<()>,
}

impl WipeState {
    /// Wipes the reserved memory region.
    ///
    /// Mirrors C `open_dice_wipe()`: map write-combined, zero, unmap, all
    /// under the instance mutex.
    fn wipe(&self) -> Result {
        let _guard = self.lock.lock();

        // SAFETY: `base`/`size` describe a valid reserved memory region;
        // `MEMREMAP_WC` matches C's `devm_memremap(..., MEMREMAP_WC)`.
        // NULL failure maps to `-ENOMEM`, same as C's ERR_PTR wrapper.
        let addr =
            unsafe { bindings::memremap(self.base, self.size, bindings::MEMREMAP_WC as c_ulong) };
        if addr.is_null() {
            return Err(ENOMEM);
        }

        // SAFETY: `addr` is a mapping of `size` bytes obtained from the
        // `memremap()` call above, so writing `size` zero bytes is in bounds.
        // The memory is reserved memory not otherwise accessed by the kernel.
        unsafe { core::ptr::write_bytes(addr.cast::<u8>(), 0, self.size) };

        // SAFETY: `addr` came from the paired `memremap()` call above and has
        // not been unmapped since.
        unsafe { bindings::memunmap(addr) };

        Ok(())
    }
}

/// Per-device driver data, analogous to `struct open_dice_drvdata`.
#[pin_data]
struct OpenDiceData {
    /// Immutable region description and wipe lock, shared with open files.
    state: Arc<WipeState>,
    /// Registered `/dev/open-dice<idx>` node; unregistered on drop.
    #[pin]
    misc: MiscDeviceRegistration<OpenDiceFile>,
}

/// File-private data type for open file descriptors.
///
/// Each open file owns an `Arc<WipeState>` clone so that operations remain
/// memory-safe even if the device is unbound while the file is still open.
struct OpenDiceFile;

#[vtable]
impl MiscDevice for OpenDiceFile {
    /// The shared instance state serves as the file's private data.
    type Ptr = Arc<WipeState>;

    fn open(_file: &File, misc: &MiscDeviceRegistration<Self>) -> Result<Self::Ptr> {
        // SAFETY: `misc` is the `misc` field of the pinned `OpenDiceData`
        // allocated by `probe()` (the only way it can exist), and that
        // allocation outlives this call, so the container pointer is valid.
        let data: &OpenDiceData =
            unsafe { &*container_of!(core::ptr::from_ref(misc), OpenDiceData, misc) };

        Ok(data.state.clone())
    }

    fn read_iter(mut kiocb: Kiocb<'_, Self::Ptr>, iov: &mut IovIterDest<'_>) -> Result<usize> {
        let state = kiocb.file();

        // Mirror C `open_dice_read()`: copy the region size out as a native
        // `unsigned long`, honoring the file position.
        let val: c_ulong = state.size as c_ulong;

        iov.simple_read_from_buffer(kiocb.ki_pos_mut(), &val.to_ne_bytes())
    }

    fn write_iter(kiocb: Kiocb<'_, Self::Ptr>, iov: &mut IovIterSource<'_>) -> Result<usize> {
        let state = kiocb.file();

        // Any write triggers a wipe; the user buffer is never dereferenced.
        state.wipe().map_err(|_| EIO)?;

        // Consume the input buffer.
        Ok(iov.len())
    }

    fn mmap(
        state: <Self::Ptr as ForeignOwnable>::Borrowed<'_>,
        _file: &File,
        vma: &VmaNew,
    ) -> Result {
        if vma.flags() & flags::MAYSHARE != 0 {
            // Do not allow userspace to modify the underlying data.
            if vma.writable() {
                return Err(EPERM);
            }

            // Ensure userspace cannot acquire VM_WRITE later. Cannot fail:
            // VM_WRITE was just found unset above.
            vma.try_clear_maywrite()?;
        }

        // Create write-combine mapping so all clients observe a wipe.
        //
        // SAFETY: `vma` is undergoing initial setup inside the mmap hook, so
        // we have exclusive access to its fields. `vm_page_prot` is only ever
        // mutated here, exactly like the C driver does via
        // `desc->page_prot = pgprot_writecombine(desc->page_prot)`. The Rust
        // `VmaNew` abstraction does not expose a safe setter for it yet.
        unsafe {
            let raw = vma.as_ptr();
            (*raw).vm_page_prot = bindings::pgprot_writecombine((*raw).vm_page_prot);
        }

        vma.set_dontcopy();
        vma.set_dontdump();

        // Map the rmem range honoring vm_pgoff, ioremap-style. This is the
        // classic-API counterpart of the C driver's
        // `mmap_action_simple_ioremap()`: it performs the same validation
        // (`__simple_ioremap_prep`) and sets the same flags.
        //
        // SAFETY: `vma.as_ptr()` is a valid VMA being initialized in this mmap
        // hook; `[base, base+size)` is a valid reserved memory region.
        to_result(unsafe {
            bindings::vm_iomap_memory(vma.as_ptr(), state.base, state.size as c_ulong)
        })
    }
}

kernel::of_device_table!(
    OF_TABLE,
    <OpenDiceDriver as platform::Driver>::IdInfo,
    [(of::DeviceId::new(c"google,open-dice"), ())]
);

/// Platform driver, analogous to `open_dice_driver` in the C code.
struct OpenDiceDriver;

impl OpenDiceDriver {
    /// Validates the reserved memory reference and builds the shared state.
    ///
    /// Mirrors the validation part of C `open_dice_probe()`.
    fn build_state(dev: &device::Device) -> Result<Arc<WipeState>> {
        let np = match dev.fwnode() {
            Some(fwnode) =>
            // SAFETY: `fwnode` borrows from a valid device and outlives the
            // raw pointer use below.
            unsafe { bindings::to_of_node(fwnode.as_raw()) },
            None => core::ptr::null_mut(),
        };

        // SAFETY: `np` is either NULL or a valid OF node owned by the device;
        // both cases are handled by `of_reserved_mem_lookup()`.
        let rmem = unsafe { bindings::of_reserved_mem_lookup(np) };
        if rmem.is_null() {
            dev_err!(dev, "failed to lookup reserved memory\n");
            return Err(EINVAL);
        }

        // SAFETY: `of_reserved_mem_lookup()` returned a pointer to a valid
        // entry of the reserved-memory table, which stays alive forever.
        let (base, size) = unsafe { ((*rmem).base, (*rmem).size) };

        if size == 0 {
            dev_err!(dev, "invalid memory region size\n");
            return Err(EINVAL);
        }

        // Mirrors the `rmem->size > ULONG_MAX` check; cannot trigger on
        // 64-bit targets where phys_addr_t fits into unsigned long.
        let size = usize::try_from(size).map_err(|_| {
            dev_err!(dev, "invalid memory region size\n");
            EINVAL
        })?;

        if base % PAGE_SIZE as bindings::phys_addr_t != 0 || size % PAGE_SIZE != 0 {
            dev_err!(dev, "memory region must be page-aligned\n");
            return Err(EINVAL);
        }

        Arc::try_pin_init(
            try_pin_init! {
                WipeState {
                    base,
                    size,
                    lock <- new_mutex!(()),
                }
            },
            GFP_KERNEL,
        )
    }
}

impl platform::Driver for OpenDiceDriver {
    type IdInfo = ();
    type Data<'bound> = OpenDiceData;

    const OF_ID_TABLE: Option<of::IdTable<Self::IdInfo>> = Some(&OF_TABLE);

    fn probe<'bound>(
        pdev: &'bound platform::Device<Core<'_>>,
        _id_info: Option<&'bound Self::IdInfo>,
    ) -> impl PinInit<Self::Data<'bound>, Error> + 'bound {
        let dev = pdev.as_ref();

        pin_init::pin_init_scope(move || {
            // Validation happens first and can fail the probe with -EINVAL,
            // exactly like the C driver.
            let state = Self::build_state(dev)?;

            // Index overflow check not needed, misc_register() will fail.
            // Note that the index is consumed even if registration fails
            // afterwards, preserving the C numbering behavior.
            let idx = DEV_IDX.fetch_add(1, Ordering::Relaxed);

            // The formatted name must live forever because
            // `MiscDeviceOptions` requires a `&'static CStr`; leak it
            // deliberately (bounded by the number of bound instances).
            let cstring = CString::try_from_fmt(fmt!("{DRIVER_NAME_PREFIX}{idx}"))?;
            let name: &'static CStr = KBox::leak(KBox::new(cstring, GFP_KERNEL)?);

            Ok(try_pin_init! {
                OpenDiceData {
                    state,
                    misc <- MiscDeviceRegistration::register(MiscDeviceOptions { name }),
                }
            })
        })
    }
}

kernel::module_platform_driver! {
    type: OpenDiceDriver,
    name: "rust_open_dice",
    authors: ["David Brazdil <dbrazdil@google.com>"],
    description: "Rust driver for Open Profile for DICE",
    license: "GPL v2",
}
